#------------------------------------------------------------------------------#
# FleCSI Gitlab CI: Main
#------------------------------------------------------------------------------#

stages:
  - Canary
  - Environment
  - Build + Unit Tests
  - Tutorial
  - Final

variables:
  COLOR_BLUE: '\033[1;34m'
  COLOR_GREEN: '\033[0;32m'
  COLOR_MAGENTA: '\033[1;35m'
  COLOR_PLAIN: '\033[0m'

include: .gitlab/environments.yml

#------------------------------------------------------------------------------#
# Formatting target.
#
# The selected image must have the required clang-format version
# installed during image creation in the 'gitlab-ci' branch.
#------------------------------------------------------------------------------#

format:diff:
  extends: .diff_format_template
  dependencies: []
  only:
    - merge_requests
  variables:
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: util-fedora-30
    FORMAT_VERSION: 8.0.0
  allow_failure: true

format:check:
  extends: .check_format_template
  needs:
    - job: format:diff
      artifacts: true
    - job: tutorial:legion # Hack to make this last. Gitlab needs some mechanism to allow this
  only:
    - merge_requests
  variables:
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: util-fedora-30

#------------------------------------------------------------------------------#
# Build and unit tests for default settings.
#
# Image: CentOS 7.8
#------------------------------------------------------------------------------#

mpich-defaults:
  extends: .defaults_build_template
  needs:
    ["mpich"]
  only:
    - merge_requests
  variables:
    ENVIRONMENT: '${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}'
    MPI_PROVIDER: mpich
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: centos-8

#------------------------------------------------------------------------------#
# Build and unit tests for Legion runtime with MPICH provider,
# and GNU compiler toolchain.
#
# Image: CentOS 7.8
#------------------------------------------------------------------------------#

mpich-legion-gnu:
  extends: .build_template
  needs:
    ["mpich-debug"]
  only:
    - merge_requests
  variables:
    ENVIRONMENT: '${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}'
    MPI_PROVIDER: mpich
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: centos-8
    BUILD_TYPE: Debug
    RUNTIME: legion
    CXX_COMPILER: g++
    CXX_FLAGS: -Wall -W -Werror -Wno-parentheses
    C_COMPILER: gcc
    C_FLAGS: ${CXX_FLAGS}
    CMAKE_OPTIONS: -DENABLE_FLOG=ON -DENABLE_HDF5=ON -DENABLE_KOKKOS=ON

mpich-legion-gnu:release:
  extends: .build_template
  needs:
    ["mpich"]
  only:
    - merge_requests
  variables:
    ENVIRONMENT: '${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}'
    MPI_PROVIDER: mpich
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: centos-8
    BUILD_TYPE: Release
    RUNTIME: legion
    CXX_COMPILER: g++
    CXX_FLAGS: -Wall -W -Werror -Wno-parentheses
    C_COMPILER: gcc
    C_FLAGS: ${CXX_FLAGS}
    CMAKE_OPTIONS: -DENABLE_FLOG=ON -DENABLE_HDF5=ON -DENABLE_KOKKOS=ON

#------------------------------------------------------------------------------#
# Build and unit tests for MPI runtime with MPICH provider,
# and GNU compiler toolchain.
#
# Image: CentOS 7.8
#------------------------------------------------------------------------------#

mpich-mpi-gnu:
  extends: .build_template
  needs:
    ["mpich-debug"]
  only:
    - merge_requests
  variables:
    ENVIRONMENT: '${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}'
    MPI_PROVIDER: mpich
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: centos-8
    BUILD_TYPE: Debug
    RUNTIME: mpi
    CXX_COMPILER: g++
    CXX_FLAGS: -Wall -W -Werror -Wno-parentheses
    C_COMPILER: gcc
    C_FLAGS: ${CXX_FLAGS}
    CMAKE_OPTIONS: -DENABLE_FLOG=ON -DENABLE_HDF5=ON

mpich-mpi-gnu:release:
  extends: .build_template
  needs:
    ["mpich"]
  only:
    - merge_requests
  variables:
    ENVIRONMENT: '${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}'
    MPI_PROVIDER: mpich
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: centos-8
    BUILD_TYPE: Release
    RUNTIME: mpi
    CXX_COMPILER: g++
    CXX_FLAGS: -Wall -W -Werror -Wno-parentheses
    C_COMPILER: gcc
    C_FLAGS: ${CXX_FLAGS}
    CMAKE_OPTIONS: -DENABLE_FLOG=ON -DENABLE_HDF5=ON

#------------------------------------------------------------------------------#
# Tutorial tests for Legion runtime with MPICH provider,
# and GNU compiler toolchain.
#
# Image: CentOS 7.8
#------------------------------------------------------------------------------#

tutorial:legion:
  extends: .tutorial_template
  needs:
    ["mpich-legion-gnu"]
  only:
    - merge_requests
  variables:
    ENVIRONMENT: '${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}'
    MPI_PROVIDER: mpich
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: centos-8
    CXX_COMPILER: g++
    CXX_FLAGS: -Wall -W -Werror -Wno-parentheses
    C_COMPILER: gcc
    C_FLAGS: ${CXX_FLAGS}

#------------------------------------------------------------------------------#
# Build and unit tests for Legion runtime with OpenMPI provider,
# and GNU compiler toolchain.
#
# Image: CentOS 7.8
#------------------------------------------------------------------------------#

openmpi-legion-gnu:
  extends: .build_template
  needs:
    ["openmpi-debug"]
  only:
    - merge_requests
  variables:
    ENVIRONMENT: '${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}'
    MPI_PROVIDER: openmpi
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: centos-8
    BUILD_TYPE: Debug
    RUNTIME: legion
    CXX_COMPILER: g++
    CXX_FLAGS: -Wall -W -Werror -Wno-parentheses
    C_COMPILER: gcc
    C_FLAGS: ${CXX_FLAGS}
    CMAKE_OPTIONS: -DENABLE_FLOG=ON -DENABLE_HDF5=ON

openmpi-legion-gnu:release:
  extends: .build_template
  needs:
    ["openmpi"]
  only:
    - merge_requests
  variables:
    ENVIRONMENT: '${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}'
    MPI_PROVIDER: openmpi
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: centos-8
    BUILD_TYPE: Release
    RUNTIME: legion
    CXX_COMPILER: g++
    CXX_FLAGS: -Wall -W -Werror -Wno-parentheses
    C_COMPILER: gcc
    C_FLAGS: ${CXX_FLAGS}
    CMAKE_OPTIONS: -DENABLE_FLOG=ON -DENABLE_HDF5=ON

#------------------------------------------------------------------------------#
# Build and unit tests for MPI runtime with OpenMPI provider,
# and GNU compiler toolchain.
#
# Image: CentOS 7.8
#------------------------------------------------------------------------------#

openmpi-mpi-gnu:
  extends: .build_template
  needs:
    ["openmpi-debug"]
  only:
    - merge_requests
  variables:
    ENVIRONMENT: '${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}'
    MPI_PROVIDER: openmpi
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: centos-8
    BUILD_TYPE: Debug
    RUNTIME: mpi
    CXX_COMPILER: g++
    CXX_FLAGS: -Wall -W -Werror -Wno-parentheses
    C_COMPILER: gcc
    C_FLAGS: ${CXX_FLAGS}
    CMAKE_OPTIONS: -DENABLE_FLOG=ON -DENABLE_HDF5=ON

openmpi-mpi-gnu:release:
  extends: .build_template
  needs:
    ["openmpi"]
  only:
    - merge_requests
  variables:
    ENVIRONMENT: '${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}'
    MPI_PROVIDER: openmpi
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: centos-8
    BUILD_TYPE: Release
    RUNTIME: mpi
    CXX_COMPILER: g++
    CXX_FLAGS: -Wall -W -Werror -Wno-parentheses
    C_COMPILER: gcc
    C_FLAGS: ${CXX_FLAGS}
    CMAKE_OPTIONS: -DENABLE_FLOG=ON -DENABLE_HDF5=ON

#------------------------------------------------------------------------------#
# Build and unit tests for Legion runtime with MPICH provider,
# and Clang compiler toolchain.
#
# Image: CentOS 7.8
#------------------------------------------------------------------------------#

mpich-legion-clang:
  extends: .build_template
  needs:
    ["mpich-clang-debug"]
  only:
    - merge_requests
  variables:
    ENVIRONMENT: '${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}'
    MPI_PROVIDER: mpich
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: clearlinux
    BUILD_TYPE: Debug
    RUNTIME: legion
    CXX_COMPILER: clang++
    CXX_FLAGS: -fcolor-diagnostics -Wall -W -Werror -Wno-parentheses
    C_COMPILER: clang
    C_FLAGS: ${CXX_FLAGS}
    CMAKE_OPTIONS: -DENABLE_FLOG=ON -DENABLE_HDF5=ON -DENABLE_KOKKOS=ON

#------------------------------------------------------------------------------#
# Build and unit tests for MPI runtime with MPICH provider,
# and Clang compiler toolchain.
#
# Image: CentOS 7.8
#------------------------------------------------------------------------------#

mpich-mpi-clang:
  extends: .build_template
  needs:
    ["mpich-clang-debug"]
  only:
    - merge_requests
  variables:
    ENVIRONMENT: '${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}'
    MPI_PROVIDER: mpich
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: clearlinux
    BUILD_TYPE: Debug
    RUNTIME: mpi
    CXX_COMPILER: clang++
    CXX_FLAGS: -fcolor-diagnostics -Wall -W -Werror -Wno-parentheses
    C_COMPILER: clang
    C_FLAGS: ${CXX_FLAGS}
    CMAKE_OPTIONS: -DENABLE_FLOG=ON -DENABLE_HDF5=ON

#------------------------------------------------------------------------------#
# Build and unit tests for MPI runtime with OpenMPI provider,
# and Clang compiler toolchain.
#
# Image: CentOS 7.8
#------------------------------------------------------------------------------#

openmpi-mpi-clang:
  extends: .build_template
  needs:
    ["openmpi-clang-debug"]
  only:
    - merge_requests
  variables:
    ENVIRONMENT: '${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}'
    MPI_PROVIDER: openmpi
    REGISTRY: gitlab.lanl.gov:5050/flecsi/flecsi
    IMAGE: clearlinux
    BUILD_TYPE: Debug
    RUNTIME: mpi
    CXX_COMPILER: clang++
    CXX_FLAGS: -fcolor-diagnostics -Wall -W -Werror -Wno-parentheses
    C_COMPILER: clang
    C_FLAGS: ${CXX_FLAGS}
    CMAKE_OPTIONS: -DENABLE_FLOG=ON -DENABLE_HDF5=ON
